FROM devopsedu/webapp

MAINTAINER Rajesh <mails4rajesh@gmail.com>

# Update Repository
RUN apt-get update -y

# Installing apache
RUN apt-get install -y apache2

# Installing php packages
RUN apt-get install -y php7.0 libapache2-mod-php7.0 php7.0-cli php7.0-common php7.0-mbstring php7.0-gd php7.0-intl php7.0-xml php7.0-mysql

# place app files
RUN rm -rf /var/www/html/*
COPY website /var/www/html/

# Direct to port 80
EXPOSE 8080

# start apache
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
